language: android

branches:
    only:
        - master

jdk:
    - oraclejdk7
    - oraclejdk8

android:
    components:
        - tools
        - platform-tools
        - build-tools-23.0.2
        - android-23
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
